name: calculator_lock
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.1.14
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.1
  uuid: ^4.5.1
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.19.0
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  logger: ^2.0.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  get: ^4.6.6

  # DI
  injectable: ^2.3.0
  get_it: ^7.6.4

  dio: ^5.3.2
  rxdart: ^0.27.7
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  json_serializable: ^6.7.1
  flutter_svg_provider: ^1.0.6
  lottie: ^2.6.0
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.3.8
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  flutter_easyloading: ^3.0.5

  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  flutter_local_notifications: ^18.0.0
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  pointycastle: ^4.0.0
  firebase_analytics: ^11.4.5
  convert: ^3.1.2
  json_annotation: ^4.9.0
  curl_logger_dio_interceptor: ^1.0.0
  widgets_to_image: ^1.0.0
  permission_handler: ^12.0.0+1
  image_gallery_saver_plus: ^4.0.1
  load_switch: ^2.2.0
  loading_animation_widget: ^1.3.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  intl_utils: ^2.8.4
  retrofit_generator: ^7.0.8
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.7
  qr_flutter: ^4.1.0
  mqtt_client: ^9.6.4
  pointycastle: ^4.0.0
  cryptography: ^2.7.0
  asn1lib: ^1.5.9
  fl_chart: ^0.70.2
  path_provider: ^2.1.5
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#17181A"
  image: assets/images/calculator.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/calculator.png

flutter_assets_generator:
  output_dir: generated
  auto_detection: true
  named_with_parent: true
  output_filename: assets
  class_name: Assets
flutter_intl:
  enabled: true
  main_locale: vi
  localizations:
    - en
    - vi
